pool:
  name: Azure Pipelines
steps:
  - task: NodeTool@0
    displayName: "Use Node 22.x"
    inputs:
      versionSpec: 22.x

  - task: Npm@0
    displayName: "npm install"
    inputs:
      cwd: dist
      arguments: "--force"

  - task: Npm@1
    displayName: "npm run build_prod"
    inputs:
      command: custom
      verbose: false
      customCommand: "run build_dev"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    inputs:
      PathtoPublish: dist
